### ISSUE TITLE
ESP-Wifi-Config/ESPWifiConfig.h:34:11: fatal error: webpages\\define_vars.h: No such file or directory

### ISSUE THREAD

**Issue by sdsalyer** [tabahi/ESP-Wifi-Config#1]
Hello,

Nifty package! I encountered issue when using it on Linux with a knockoff D1 Mini (ESP8266) board. I was able to work around it by editing the installed library files (see diff/patch below). I still get some warnings about "c++ forbids converting a string constant to char*" but it seems to operate fine.

**System:**

```sh
OS: Arch Linux x86_64
Kernel: 6.11.6-zen1-1-zen

% arduino-cli version
arduino-cli  Version: 1.0.3-arch Commit: 8b6ad258e88581a9e77b2eede65aeeeeb265008c Date:

% arduino-cli lib list | grep ESP-Wifi-Config
ESP-Wifi-Config                                  2.2.5     -         user     -
```

**Command and error message:**

```sh
% arduino-cli compile --fqbn esp8266:esp8266:d1_mini
In file included from /home/berts/dev/ee/d1_mini/hmm_temp/hmm_temp.ino:22:
/home/berts/Arduino/libraries/ESP-Wifi-Config/ESPWifiConfig.h:34:11: fatal error: webpages\\define_vars.h: No such file or directory
   34 | #include  "webpages\\define_vars.h"
      |           ^~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

**Fix:**

I am new with this, but I believe the below patch solves the issue. I've read that double-quotes are for including from a sketch, while angle brackets are for including within a library.

```diff
diff --git a/ESPWifiConfig.h b/ESPWifiConfig.h
index c440d0a..74b4875 100644
--- a/ESPWifiConfig.h
+++ b/ESPWifiConfig.h
@@ -31,7 +31,7 @@
 
 #include <EEPROM.h>
 #include <DNSServer.h>
-#include  "webpages\\define_vars.h"
+#include <webpages/define_vars.h>
 
  
```

**Comment by tabahi** [comment]
Thanks for the fix. You are right, I never tested it on linux which would definitely have a problem with a windows' backslash path  "webpages\\define_vars.h".

Now I have set it to <webpages/define_vars.h> and it compiles on Windows.

**Comment by sdsalyer** [comment]
Glad I could help! Do you have plans/ETA to create a new release and update the Arduino package registry? No pressure from me of course, just wanted to be on the lookout if so. Thanks again for sharing your project!
